version: '2'

services:
  application:
      container_name: ec_cube_application
      image: debian
      volumes:
          - ./:/var/www/ec-cube
  workspace:
      container_name: ec_cube_workspace
      image: brandit-system-ec-cube_workspace
      volumes_from:
          - application
      tty: true
  php-fpm:
      container_name: ec_cube_php-fpm
      image: framgia/laravel-php-fpm
      volumes_from:
          - application
      expose:
          - "9000"
      links:
          - workspace
  nginx:
      container_name: ec_cube_nginx
      image: framgia/laravel-nginx
      volumes_from:
          - data
          - logs
          - application
      ports:
          - "2020:80"
      links:
          - php-fpm
  data:
      container_name: ec_cube_data
      image: debian
      volumes:
          - .docker/mysql:/var/lib/mysql
          - .docker/data:/data
  logs:
      container_name: ec_cube_logs
      image: debian
      volumes:
          - .docker/logs/nginx:/var/log/nginx
          - .docker/logs/mongodb:/var/log/mongodb
  mysql:
      container_name: ec_cube_mysql
      image: mysql:5.7
      volumes_from:
          - data
          - logs
      expose:
          - "3306"
      environment:
          MYSQL_DATABASE: ec_cube
          MYSQL_USER: root
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
      container_name: ec_cube_phpmyadmin
      image: phpmyadmin/phpmyadmin
      environment:
          PMA_ARBITRARY: 1
          MYSQL_USER: root
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: root
      ports:
          - "8080:80"
